Update Dev-X86.conf
Remove nft-qos, bypass/passwall and related packages

Because of unknown error, after last time add some apps
Too many error, one of those is:
error: ext4_allocate_best_fit_partial: failed to allocate 1950 blocks, out of space?

Just try it