Update Dev-X86.conf
avoid ddnsto because of:
 make[3] -C feeds/kenzo/ddnsto compile
    ERROR: package/feeds/kenzo/ddnsto failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 1

make[3] -C feeds/kenzo/ddnsto compile
    ERROR: package/feeds/kenzo/ddnsto failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 1