Update cm520-canbox.config
No CONFIG_PACKAGE_libmbedtls Because error list below:
Configuring ppp-mod-pppoe.
 * check_data_file_clashes: Package libustream-openssl20201210 wants to install file /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/lib/libustream-ssl.so
Configuring luci-i18n-nlbwmon-zh-cn.
	But that file is already provided by package  * libustream-mbedtls20201210
 * opkg_install_cmd: Cannot install package libustream-openssl20201210.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[1]: *** [package/Makefile:111: /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_install] Error 2
Configuring coreutils-nohup.
make[2]: Leaving directory '/workdir/openwrt'
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.