Update Dev-MobiPromo-CM520-79F.conf
Trying:
1. all libustream-openssl = m （in 2 places)
According to: Libustream-wolfssl clashing with libustream-openssl
https://forum.openwrt.org/t/libustream-wolfssl-clashing-with-libustream-openssl/73423

Error:
Configuring coreutils-nohup.
 * check_data_file_clashes: Package libustream-openssl20201210 wants to install file /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/lib/libustream-ssl.so
	But that file is already provided by package  * libustream-mbedtls20201210
 * opkg_install_cmd: Cannot install package libustream-openssl20201210.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[1]: *** [package/Makefile:111: /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_install] Error 2
make[2]: Leaving directory '/workdir/openwrt'
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.